version: '3.0'

services:
  frontend:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
       - ../../logs:/application/logs
    image: soc-frontend:sandbox
    command: [ "./sandserver",  "4021"]
    ports:
      - "4021:4021"
    networks:
      - soc-network

networks:
  soc-network:
